version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build: ./backend
    container_name: flask_backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_database
      - POSTGRES_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"

volumes:
  pgdata: